//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketCrawler.Worker.TicketCrawlerServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TicketCrawlerServer.ITicketCrawlerServer")]
    public interface ITicketCrawlerServer {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITicketCrawlerServer/RegisterWorker")]
        void RegisterWorker(string workerEndpointUrl);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITicketCrawlerServer/RegisterWorker")]
        System.Threading.Tasks.Task RegisterWorkerAsync(string workerEndpointUrl);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITicketCrawlerServer/MakeRequest")]
        void MakeRequest(TicketCrawler.Core.Event.EventRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITicketCrawlerServer/MakeRequest")]
        System.Threading.Tasks.Task MakeRequestAsync(TicketCrawler.Core.Event.EventRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITicketCrawlerServerChannel : TicketCrawler.Worker.TicketCrawlerServer.ITicketCrawlerServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TicketCrawlerServerClient : System.ServiceModel.ClientBase<TicketCrawler.Worker.TicketCrawlerServer.ITicketCrawlerServer>, TicketCrawler.Worker.TicketCrawlerServer.ITicketCrawlerServer {
        
        public TicketCrawlerServerClient() {
        }
        
        public TicketCrawlerServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TicketCrawlerServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TicketCrawlerServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TicketCrawlerServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegisterWorker(string workerEndpointUrl) {
            base.Channel.RegisterWorker(workerEndpointUrl);
        }
        
        public System.Threading.Tasks.Task RegisterWorkerAsync(string workerEndpointUrl) {
            return base.Channel.RegisterWorkerAsync(workerEndpointUrl);
        }
        
        public void MakeRequest(TicketCrawler.Core.Event.EventRequest request) {
            base.Channel.MakeRequest(request);
        }
        
        public System.Threading.Tasks.Task MakeRequestAsync(TicketCrawler.Core.Event.EventRequest request) {
            return base.Channel.MakeRequestAsync(request);
        }
    }
}
